insert into Etiquetas (id_video, nombre) values (9, 'Drinking Buddies');
insert into Etiquetas (id_video, nombre) values (4, 'Sharpe''s Sword');
insert into Etiquetas (id_video, nombre) values (5, 'Vendetta');
insert into Etiquetas (id_video, nombre) values (26, 'Class of Nuke ''Em High Part II: Subhumanoid Meltdown');
insert into Etiquetas (id_video, nombre) values (17, 'Caótica Ana');
insert into Etiquetas (id_video, nombre) values (7, 'Welcome to the Space Show (Uchû shô e yôkoso)');
insert into Etiquetas (id_video, nombre) values (4, 'Ghost and Mrs. Muir, The');
insert into Etiquetas (id_video, nombre) values (27, 'Feel the Noise');
insert into Etiquetas (id_video, nombre) values (2, 'Bread and Chocolate (Pane e cioccolata)');
insert into Etiquetas (id_video, nombre) values (10, 'Gold Diggers of 1933');
insert into Etiquetas (id_video, nombre) values (30, 'Inbetweeners 2, The');
insert into Etiquetas (id_video, nombre) values (2, 'Passchendaele');
insert into Etiquetas (id_video, nombre) values (20, 'Mystery Train');
insert into Etiquetas (id_video, nombre) values (5, 'Aujourd''hui');
insert into Etiquetas (id_video, nombre) values (10, 'BloodRayne');
insert into Etiquetas (id_video, nombre) values (13, 'Return of the Living Dead: Necropolis');
insert into Etiquetas (id_video, nombre) values (23, 'Human Resources (Ressources humaines)');
insert into Etiquetas (id_video, nombre) values (21, 'Jarhead');
insert into Etiquetas (id_video, nombre) values (11, 'Raw Deal: A Question of Consent');
insert into Etiquetas (id_video, nombre) values (30, 'One Man Up (L''uomo in più)');
insert into Etiquetas (id_video, nombre) values (29, 'Tank Girl');
insert into Etiquetas (id_video, nombre) values (15, 'Caught Up');
insert into Etiquetas (id_video, nombre) values (27, 'Film Unfinished, A (Shtikat Haarchion)');
insert into Etiquetas (id_video, nombre) values (16, 'Taking Care of Business');
insert into Etiquetas (id_video, nombre) values (28, 'Perfect Blue');
insert into Etiquetas (id_video, nombre) values (7, 'Camille Claudel');
insert into Etiquetas (id_video, nombre) values (26, 'Game 6');
insert into Etiquetas (id_video, nombre) values (21, 'Young Lieutenant, The (Le petit lieutenant)');
insert into Etiquetas (id_video, nombre) values (14, 'And Now My Love (Toute une vie)');
insert into Etiquetas (id_video, nombre) values (29, 'Godzilla, King of the Monsters! (Kaijû-ô Gojira)');
insert into Etiquetas (id_video, nombre) values (9, 'Free to Play');
insert into Etiquetas (id_video, nombre) values (11, 'Hoodwinked Too! Hood vs. Evil');
insert into Etiquetas (id_video, nombre) values (1, 'Player, The');
insert into Etiquetas (id_video, nombre) values (15, 'Young Goethe in Love');
insert into Etiquetas (id_video, nombre) values (20, 'Creature from Black Lake ');
insert into Etiquetas (id_video, nombre) values (15, 'Shipping News, The');
insert into Etiquetas (id_video, nombre) values (11, 'Shed No Tears (Känn ingen sorg)');
insert into Etiquetas (id_video, nombre) values (16, 'Dead, The');
insert into Etiquetas (id_video, nombre) values (1, 'Alone in the Wilderness');
insert into Etiquetas (id_video, nombre) values (29, 'Robber, The (Der Räuber)');
