insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (22, 25, 'Adventures of Sebastian Cole, The', '2011/10/28', true);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (12, 7, 'Shakespeare in Love', '2011/12/17', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (9, 10, 'Extraordinary Measures', '2017/04/02', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (4, 21, 'Loaded', '2015/12/13', true);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (26, 23, 'Zatoichi''s Pilgrimage (Zatôichi umi o wataru) (Zatôichi 14)', '2013/05/29', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (20, 21, 'Arcana', '2015/11/29', true);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (1, 2, 'In the Soup', '2015/06/10', true);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (19, 27, 'Loco Love (Mi Casa, Su Casa)', '2005/07/03', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (15, 9, 'Thief, The (Vor)', '2021/08/24', true);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (10, 23, 'Django', '2010/07/16', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (24, 21, 'Arch of Triumph', '2019/03/11', true);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (20, 24, 'Born Wild', '2010/05/28', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (26, 24, 'Ishaqzaade', '2011/10/08', true);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (21, 12, 'Wisegirls', '2007/02/21', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (26, 5, 'Son of Babylon (Syn Babilonu)', '2010/01/09', true);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (28, 7, 'United 93', '2005/05/28', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (7, 20, 'One Week', '2012/10/02', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (16, 29, 'Haute Cuisine', '2020/11/01', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (1, 26, 'Love Loves Coincidences', '2012/10/18', true);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (5, 1, 'Painting, The (Tableau, Le)', '2019/09/08', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (12, 28, 'Murder on a Sunday Morning (Un coupable idéal)', '2019/07/12', true);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (5, 29, 'The Borderlands', '2013/07/07', true);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (8, 5, 'Seconds', '2008/04/24', true);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (4, 26, 'The Blood of Fu Manchu', '2020/06/14', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (27, 23, 'I Stand Alone (Seul contre tous)', '2012/09/24', true);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (2, 10, 'My Neighbor Totoro (Tonari no Totoro)', '2013/09/27', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (10, 9, 'Spontaneous Combustion', '2018/07/23', true);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (24, 10, 'Remember the Night', '2017/05/12', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (4, 20, 'Crash', '2008/11/24', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (11, 19, 'Wash, The', '2021/07/19', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (17, 29, '2AM: The Smiling Man', '2021/11/07', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (12, 21, 'Better Than Chocolate', '2011/09/29', true);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (6, 12, 'Shoot ''Em Up', '2019/12/01', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (5, 26, 'Bummer (Bumer)', '2004/06/04', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (13, 6, 'Dolemite', '2012/02/29', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (8, 27, 'Hallåhallå', '2018/08/12', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (13, 4, 'Amazing Journey: The Story of The Who', '2005/06/05', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (11, 18, 'Through the Olive Trees (Zire darakhatan zeyton)', '2012/09/21', true);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (2, 16, 'Time Walker (a.k.a. Being From Another Planet)', '2014/09/11', true);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (30, 14, 'Last Tango in Paris (Ultimo tango a Parigi)', '2009/04/27', true);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (12, 29, 'Seven Years in Tibet', '2006/01/07', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (11, 27, 'Frankenfish', '2014/01/21', true);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (23, 19, 'Jauja', '2008/07/28', true);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (14, 22, 'Against the Dark', '2009/08/28', true);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (3, 11, 'Hollywood Complex, The', '2015/10/06', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (4, 4, 'Un Poliziotto Scomodo', '2017/12/13', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (2, 6, 'Needful Things', '2005/12/23', true);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (6, 26, 'Careful', '2012/07/13', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (22, 10, 'At the Earth''s Core', '2008/05/24', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (14, 21, 'Haaveiden kehä', '2013/10/19', true);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (30, 29, 'Treatment, The', '2016/03/03', true);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (25, 28, 'Thing from Another World, The', '2015/02/21', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (27, 30, 'Knight of Cups', '2020/04/07', true);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (29, 11, 'Willow Tree, The (Beed-e majnoon)', '2006/01/14', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (15, 10, 'Went to Coney Island on a Mission From God... Be Back by Five', '2006/02/11', true);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (21, 2, 'Yumurta (Egg)', '2021/07/28', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (27, 6, 'At First Sight (Entre Nous) (Coup de foudre)', '2010/07/15', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (17, 23, 'Murder by Contract', '2004/11/28', true);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (4, 4, 'Merchant of Venice, The', '2013/11/14', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (21, 25, 'I Like It Like That', '2016/02/06', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (3, 10, 'Blue Streak', '2006/07/27', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (7, 15, 'Doulos, Le', '2010/03/27', true);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (17, 5, 'True Love', '2014/02/13', true);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (1, 28, 'Rio', '2019/02/06', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (20, 2, 'Stuart Saves His Family', '2004/03/30', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (2, 14, 'Whole Ten Yards, The', '2019/08/17', true);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (20, 13, 'Inequality for All', '2006/11/02', true);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (22, 27, 'Wanted: Dead or Alive', '2020/05/13', true);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (5, 28, 'Emmanuel''s Gift', '2013/12/20', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (4, 1, 'Red Army', '2009/06/24', true);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (25, 9, 'Faust', '2011/11/21', true);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (4, 23, 'Flying Down to Rio', '2009/06/30', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (27, 8, 'Happy Event, A (Un Heureux Evénement)', '2010/04/22', true);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (23, 12, 'You Don''t Mess with the Zohan', '2005/10/10', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (6, 22, 'Lady Death', '2013/08/08', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (17, 9, 'D2: The Mighty Ducks', '2021/07/31', true);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (23, 10, 'Leopard Man, The', '2019/02/17', false);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (22, 15, 'Red Garters', '2019/10/19', true);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (14, 26, 'Beowulf & Grendel', '2015/01/25', true);
insert into Playlist (id_usuario, id_video, nombre, fec_alta, publico) values (3, 16, 'Firewalker', '2007/06/22', false);
